name: Github Actions

on:
  push:
    branches:
      - fix

permissions:
  contents: write

jobs:
  typo-fix:
    name: Auto Fix Spelling
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Print current branch
        run: |
          echo "Current branch: $GITHUB_REF"
          echo "Short branch name: ${GITHUB_REF#refs/heads/}"

      - name: Run misspell fixer
        uses: sobolevn/misspell-fixer-action@master
        with:
          options: "-r -d -v ./"

      - name: Commit and push corrected files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add .
          if git diff --cached --quiet; then
            echo "No spelling changes found."
          else
            git commit -m "Auto-fix spelling via GitHub Actions"
            git push origin fix
            echo "Spelling fixes pushed to 'fix' branch."
          fi
