name: Github Actions

on:
  push:
    branches: fix

permissions:
  contents: write
  pull-requests: write

jobs:
  typo-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fix spelling mistakes
        uses: sobolevn/misspell-fixer-action@master
        with:
          options: "-r ."

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -B auto-typos-fix
          git add .

          # if git diff --cached --quiet; then
          #   echo "No changes detected. Skipping commit and PR creation."
          #   echo "no_changes=true" >> $GITHUB_ENV
          # else
          git commit -m "Fix typos via GitHub Action"
          git push origin auto-typos-fix --force
          # echo "no_changes=false" >> $GITHUB_ENV
          # fi

      - name: Create Pull Request
        if: env.no_changes == 'false'
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          gh auth login --with-token <<< "$PAT_TOKEN"
          gh pr create -B master -H auto-typos-fix \
            --title "Fix typos automatically" \
            --body "Created by GitHub Action"


  
