name: Github Actions

on:
  push:
    branches:
      - fix

permissions:
  contents: write

jobs:
  typo-fix:
    name: Auto Fix Spelling
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run misspell fixer
        uses: sobolevn/misspell-fixer-action@master
        with:
          options: "-r -d -v ./ | grep 'Changed file'"

      - name: Commit and push corrected files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add .
          if git diff --cached --quiet; then
            echo "No spelling changes found."
          else
            git commit -m "Auto-fix spelling via GitHub Actions"
            git push origin fix
            echo "Spelling fixes pushed to 'fix' branch."
          fi

 
      # - name: Create Pull Request
      #   if: ${{ always() }}
      #   env:
      #     PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      #   run: |
      #      gh auth login --with-token <<< "$PAT_TOKEN"
      #       if gh pr view fix --base master >/dev/null 2>&1; then
      #         echo "A pull request from fix to master already exists. Skipping creation."
      #       else
      #         if ! git diff --quiet origin/master..origin/fix; then
      #           gh pr create -B master -H fix \
      #             --title "Fix typos automatically" \
      #             --body "Created by GitHub Action"
      #         else
      #           echo "No changes between master and fix; skipping PR."
      #         fi
      #       fi



  
